apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9187"
    sourcegraph.prometheus/scrape: "true"
  labels:
    app: db-codeintel
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
  name: db-codeintel
spec:
  ports:
  - name: pgsql
    port: 5432
    targetPort: pgsql
  selector:
    app: db-codeintel
  type: ClusterIP
